/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mlauncher;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JEditorPane;

/**
 *
 * @author panqu
 */
public final class LauncherNews extends javax.swing.JPanel {

    /**
     * Creates new form LauncherNews
     * @throws java.io.IOException
     */
    public LauncherNews() throws IOException {
        initComponents();
        setPreferredSize( new Dimension( 350, 300 ) );
        setVisible(true);
        LeerHTML();

    }
    
    public void LeerHTML() throws MalformedURLException, IOException{
        try
	{
        URL u=new URL("https://hugo1568.github.io/Basic-bad-written-java-mod-downloader/launcher/upload/news.html");
	JEditorPane ed2=new JEditorPane(u);
        ed2.setEditable(false);
	add(ed2);
	setVisible(true);
	setSize(600,600);
	//setDefaultCloseOperation(EXIT_ON_CLOSE);
	}
	catch(Exception e)
	{
		System.out.println("Some problem has occured"+e.getMessage());
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
