/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mlauncher;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author panqu
 */
public class ServerData extends javax.swing.JPanel {

    /**
     * Creates new form ServerData
     */
    public ServerData() {
        initComponents();
        setPreferredSize( new Dimension( 400, 100 ) );
        setVisible(true);
        tfMCType.setEditable(false);
        tfMCVersion.setEditable(false);
        tfModsCount.setEditable(false);
        
        String ServerData;
        ServerData = readHTML();
        String[] data;
        data = ServerData.split(",");
        
        tfMCType.setText(data[0]);
        tfMCVersion.setText(data[1]);
        tfModsCount.setText(data[2]);
    }

    private String readHTML(){
        String line;
        line = "x";
        try {
             
            URL url = new URL("https://hugo1568.github.io/Basic-bad-written-java-mod-downloader/launcher/upload/serverversion.html");
            try (BufferedReader in = new BufferedReader(new InputStreamReader(url.openStream()))) {
                line = in.readLine();
            }
        }
        catch (MalformedURLException e) {
            System.out.println("Malformed URL: " + e.getMessage());
        }
        catch (IOException e) {
            System.out.println("I/O Error: " + e.getMessage());
        }
        return line;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfMCType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMCVersion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfModsCount = new javax.swing.JTextField();

        jLabel1.setText("Tipo de MC:");
        add(jLabel1);

        tfMCType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMCType.setText("  NO PREMIUM  ");
        tfMCType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMCTypeActionPerformed(evt);
            }
        });
        add(tfMCType);

        jLabel2.setText("Version de MC:");
        add(jLabel2);

        tfMCVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMCVersion.setText("  1.16.2  ");
        tfMCVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMCVersionActionPerformed(evt);
            }
        });
        add(tfMCVersion);

        jLabel3.setText("Número de mods:");
        add(jLabel3);

        tfModsCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfModsCount.setText("  256  ");
        tfModsCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModsCountActionPerformed(evt);
            }
        });
        add(tfModsCount);
    }// </editor-fold>//GEN-END:initComponents

    private void tfMCTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMCTypeActionPerformed
        //
    }//GEN-LAST:event_tfMCTypeActionPerformed

    private void tfMCVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMCVersionActionPerformed
        //
    }//GEN-LAST:event_tfMCVersionActionPerformed

    private void tfModsCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModsCountActionPerformed
        //
    }//GEN-LAST:event_tfModsCountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfMCType;
    private javax.swing.JTextField tfMCVersion;
    private javax.swing.JTextField tfModsCount;
    // End of variables declaration//GEN-END:variables
}
